### ISSUE TITLE
bs4 bug

### ISSUE THREAD

**Issue by john-livingston** [jpdeleon/exofop#1]
when calling script, e.g. get_links --epic 211319617

Traceback (most recent call last):
  File "/home/jhl/miniconda3/envs/py3/bin/get_links", line 4, in <module>
    __import__('pkg_resources').run_script('exofop==0.1.1', 'get_links')
  File "/home/jhl/miniconda3/envs/py3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/jhl/miniconda3/envs/py3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/jhl/miniconda3/envs/py3/lib/python3.6/site-packages/exofop-0.1.1-py3.6.egg/EGG-INFO/scripts/get_links", line 23, in <module>
  File "/home/jhl/miniconda3/envs/py3/lib/python3.6/site-packages/exofop-0.1.1-py3.6.egg/exofop/scrape.py", line 108, in get_all_links
  File "/home/jhl/miniconda3/envs/py3/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by jpdeleon** [comment]
Fixed by adding "lxml" dependency in the setup.py

**Comment by yehyabelhadad** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @dahcorn, @xcosmosbox, @Omar-kh, @ljshwyykl, @priom, @cufarvid, @donsn, @lispc, @TLii, @seguidor777, @xesrevinu, @rongzhou, @samrecio, @Thundercorsua, @s2je77, @alexstrassheim, @louyongjiu, @tuwid, @yanbeizhang, @shibasisp, @parvezhasan199, @Babak64, @mwilborne, @mamphis, @rayvinvincent, @chris415, @htalet, @giraygokirmak, @willydavid1, @daltroaugusto, @featorres, @hclabxing, @LambdaVex, @ali4heydari, @romankessler, @lawrence-iviani, @regiakb, @PuhlUP, @afterthought325, @cryptooooooo, @dkalvelis, @wcervini, @ajbmachon, @agarciarsu, @kittipat1413, @HT808s, @abdikoodhaa, @Blaze287, @tjd-dev, @jianghuife
